import { ExerciseDefinition } from '../types/training';
import { MuscleGroupId } from '../types/muscle';

const exercise = (
  id: string, name: string, primaryMuscle: MuscleGroupId,
  secondaryMuscles: MuscleGroupId[], equipment: string,
  tracking: ExerciseDefinition['tracking'] = 'weighted'
): ExerciseDefinition => ({ id, name, primaryMuscle, secondaryMuscles, equipment, tracking });

// Explicit IDs remain stable when labels or media change. This is reference data, never user history.
export const EXERCISES: ExerciseDefinition[] = [
  exercise('barbell-bench', 'Barbell Bench Press', 'chest', ['front_delts', 'triceps'], 'Barbell'),
  exercise('incline-barbell-bench', 'Incline Barbell Bench Press', 'chest', ['front_delts', 'triceps'], 'Barbell'),
  exercise('dumbbell-bench', 'Dumbbell Bench Press', 'chest', ['front_delts', 'triceps'], 'Dumbbells'),
  exercise('incline-dumbbell-press', 'Incline Dumbbell Press', 'chest', ['front_delts', 'triceps'], 'Dumbbells'),
  exercise('machine-chest-press', 'Machine Chest Press', 'chest', ['front_delts', 'triceps'], 'Machine'),
  exercise('cable-chest-press', 'Cable Chest Press', 'chest', ['front_delts', 'triceps'], 'Cable'),
  exercise('pec-deck', 'Pec Deck', 'chest', [], 'Machine'),
  exercise('cable-fly', 'Cable Fly', 'chest', ['front_delts'], 'Cable'),
  exercise('low-high-fly', 'Low-to-High Cable Fly', 'chest', ['front_delts'], 'Cable'),
  exercise('high-low-fly', 'High-to-Low Cable Fly', 'chest', [], 'Cable'),
  exercise('chest-dips', 'Chest Dips', 'chest', ['triceps', 'front_delts'], 'Parallel bars', 'bodyweight'),
  exercise('push-up', 'Push-Ups', 'chest', ['triceps', 'front_delts'], 'Bodyweight', 'bodyweight'),
  exercise('wide-lat-pulldown', 'Wide Grip Lat Pulldown', 'lats', ['biceps', 'upper_back'], 'Cable'),
  exercise('close-lat-pulldown', 'Close Grip Lat Pulldown', 'lats', ['biceps', 'upper_back'], 'Cable'),
  exercise('pull-up', 'Pull-Up', 'lats', ['biceps', 'upper_back'], 'Pull-up bar', 'bodyweight'),
  exercise('chin-up', 'Chin-Up', 'lats', ['biceps'], 'Pull-up bar', 'bodyweight'),
  exercise('dumbbell-row', 'Dumbbell Row', 'lats', ['upper_back', 'biceps'], 'Dumbbell'),
  exercise('single-cable-row', 'Single Arm Cable Row', 'lats', ['upper_back', 'biceps'], 'Cable'),
  exercise('straight-arm-pulldown', 'Straight Arm Pulldown', 'lats', [], 'Cable'),
  exercise('barbell-row', 'Barbell Row', 'upper_back', ['lats', 'biceps', 'rear_delts'], 'Barbell'),
  exercise('seated-cable-row', 'Seated Cable Row', 'upper_back', ['lats', 'biceps'], 'Cable'),
  exercise('chest-supported-row', 'Chest Supported Row', 'upper_back', ['lats', 'rear_delts', 'biceps'], 'Dumbbells'),
  exercise('t-bar-row', 'T-Bar Row', 'upper_back', ['lats', 'biceps'], 'Machine'),
  exercise('deadlift', 'Deadlift', 'glutes', ['hamstrings', 'upper_back', 'traps', 'forearms'], 'Barbell'),
  exercise('barbell-shrug', 'Barbell Shrug', 'traps', ['forearms'], 'Barbell'),
  exercise('dumbbell-shrug', 'Dumbbell Shrug', 'traps', ['forearms'], 'Dumbbells'),
  exercise('cable-shrug', 'Cable Shrug', 'traps', [], 'Cable'),
  exercise('seated-db-shoulder-press', 'Seated Dumbbell Shoulder Press', 'front_delts', ['side_delts', 'triceps'], 'Dumbbells'),
  exercise('barbell-overhead-press', 'Barbell Overhead Press', 'front_delts', ['side_delts', 'triceps'], 'Barbell'),
  exercise('machine-shoulder-press', 'Machine Shoulder Press', 'front_delts', ['side_delts', 'triceps'], 'Machine'),
  exercise('dumbbell-front-raise', 'Dumbbell Front Raise', 'front_delts', [], 'Dumbbells'),
  exercise('dumbbell-lateral-raise', 'Dumbbell Lateral Raise', 'side_delts', ['traps'], 'Dumbbells'),
  exercise('cable-lateral-raise', 'Cable Lateral Raise', 'side_delts', ['traps'], 'Cable'),
  exercise('machine-lateral-raise', 'Machine Lateral Raise', 'side_delts', [], 'Machine'),
  exercise('rear-delt-fly', 'Rear Delt Fly', 'rear_delts', ['upper_back'], 'Dumbbells'),
  exercise('reverse-pec-deck', 'Reverse Pec Deck', 'rear_delts', ['upper_back'], 'Machine'),
  exercise('face-pull', 'Face Pull', 'rear_delts', ['traps', 'upper_back'], 'Cable'),
  exercise('barbell-curl', 'Barbell Curl', 'biceps', ['forearms'], 'Barbell'),
  exercise('ez-bar-curl', 'EZ Bar Curl', 'biceps', ['forearms'], 'EZ bar'),
  exercise('dumbbell-curl', 'Dumbbell Curl', 'biceps', ['forearms'], 'Dumbbells'),
  exercise('incline-dumbbell-curl', 'Incline Dumbbell Curl', 'biceps', [], 'Dumbbells'),
  exercise('hammer-curl', 'Hammer Curl', 'biceps', ['forearms'], 'Dumbbells'),
  exercise('preacher-curl', 'Preacher Curl', 'biceps', [], 'EZ bar'),
  exercise('cable-curl', 'Cable Curl', 'biceps', [], 'Cable'),
  exercise('triceps-pushdown', 'Triceps Pushdown', 'triceps', [], 'Cable'),
  exercise('rope-pushdown', 'Rope Pushdown', 'triceps', [], 'Cable'),
  exercise('overhead-cable-extension', 'Overhead Cable Extension', 'triceps', [], 'Cable'),
  exercise('skull-crusher', 'Skull Crushers', 'triceps', [], 'EZ bar'),
  exercise('close-grip-bench', 'Close Grip Bench Press', 'triceps', ['chest', 'front_delts'], 'Barbell'),
  exercise('triceps-dips', 'Triceps Dips', 'triceps', ['chest', 'front_delts'], 'Parallel bars', 'bodyweight'),
  exercise('wrist-curl', 'Wrist Curl', 'forearms', [], 'Dumbbells'),
  exercise('reverse-wrist-curl', 'Reverse Wrist Curl', 'forearms', [], 'Dumbbells'),
  exercise('reverse-curl', 'Reverse Curl', 'forearms', ['biceps'], 'EZ bar'),
  exercise('barbell-squat', 'Barbell Squat', 'quads', ['glutes', 'adductors'], 'Barbell'),
  exercise('smith-squat', 'Smith Machine Squat', 'quads', ['glutes'], 'Smith machine'),
  exercise('hack-squat', 'Hack Squat', 'quads', ['glutes'], 'Machine'),
  exercise('leg-press', 'Leg Press', 'quads', ['glutes'], 'Machine'),
  exercise('leg-extension', 'Leg Extension', 'quads', [], 'Machine'),
  exercise('bulgarian-split-squat', 'Bulgarian Split Squat', 'quads', ['glutes'], 'Dumbbells'),
  exercise('walking-lunge', 'Walking Lunge', 'quads', ['glutes', 'hamstrings'], 'Dumbbells'),
  exercise('romanian-deadlift', 'Romanian Deadlift', 'hamstrings', ['glutes', 'forearms'], 'Barbell'),
  exercise('stiff-leg-deadlift', 'Stiff Leg Deadlift', 'hamstrings', ['glutes'], 'Barbell'),
  exercise('lying-leg-curl', 'Leg Curl', 'hamstrings', [], 'Machine'),
  exercise('seated-leg-curl', 'Seated Leg Curl', 'hamstrings', [], 'Machine'),
  exercise('good-morning', 'Good Morning', 'hamstrings', ['glutes'], 'Barbell'),
  exercise('hip-thrust', 'Hip Thrust', 'glutes', ['hamstrings'], 'Barbell'),
  exercise('glute-bridge', 'Glute Bridge', 'glutes', ['hamstrings'], 'Bodyweight', 'bodyweight'),
  exercise('cable-kickback', 'Cable Kickback', 'glutes', [], 'Cable'),
  exercise('standing-calf-raise', 'Standing Calf Raise', 'calves', [], 'Machine'),
  exercise('seated-calf-raise', 'Seated Calf Raise', 'calves', [], 'Machine'),
  exercise('leg-press-calf-raise', 'Leg Press Calf Raise', 'calves', [], 'Machine'),
  exercise('hanging-leg-raise', 'Hanging Leg Raise', 'abs', ['forearms'], 'Pull-up bar', 'bodyweight'),
  exercise('cable-crunch', 'Cable Crunch', 'abs', [], 'Cable'),
  exercise('crunch', 'Crunch', 'abs', [], 'Bodyweight', 'bodyweight'),
  exercise('decline-sit-up', 'Decline Sit-Up', 'abs', [], 'Bench', 'bodyweight'),
  exercise('ab-wheel', 'Ab Wheel', 'abs', ['lats'], 'Ab wheel', 'bodyweight'),
  exercise('plank', 'Plank', 'abs', [], 'Bodyweight', 'timed'),
  exercise('hip-adduction', 'Hip Adduction', 'adductors', [], 'Machine'),
  exercise('cable-adduction', 'Cable Hip Adduction', 'adductors', [], 'Cable'),
  exercise('hip-abduction', 'Hip Abduction', 'abductors', ['glutes'], 'Machine'),
];

export const EXERCISE_BY_ID = new Map(EXERCISES.map((item) => [item.id, item]));
